from setuptools import setup, find_namespace_packages

setup(
    name = "ai_applications",
    version = "0.0.1",
    description = "ai_applications",
    long_description = "",

    packages = find_namespace_packages(include=['common', 'common.*', 'face_recognize_demo', 'face_recognize_demo.*',
                                                'facemask_demo', 'facemask_demo.*', 'object_detection_demo', 'object_detection_demo.*',
                                                'style_transfer_demo', 'style_transfer_demo.*', 'yanshee_pose_imitate_demo', 'yanshee_pose_imitate_demo.*', 'photo_to_cartoon_demo', 'photo_to_cartoon_demo.*', 'smart_photo_studio_demo', 'smart_photo_studio_demo.*']),

    package_data = {"common":["*"], 
                    "common.resource":["*"],
                    "common.resource.font":["*"],
                    "common.ui":["*"],
                    "common.ui.commonDialog":["*"],
                    "common.ui.bubbleDialog":["*"],
                    "common.ui.bubbleDialog.resource":["*"],
                    "common.ui.bubbleDialog.resource.images":["*"],
                    "common.ui.bubbleDialog.resource.qss":["*"],
                    "common.ui.loading":["*"],
                    "common.ui.loading.resource":["*"],
                    "common.ui.loading.resource.images":["*"],
                    "common.ui.loading.resource.qss":["*"],

                    "common.ui.gallery":["*"],
                    "common.ui.gallery.resource":["*"],
                    "common.ui.gallery.resource.images":["*"],
                    "common.ui.gallery.resource.qss":["*"],

                    "common.ui.slider":["*"],
                    "common.ui.slider.resource.images":["*"],
                    "common.ui.slider.resource.qss":["*"],
                    "common.utility":["*"],
                    "common.utility.resources":["*"],
                    "common.utility.locale.en.LC_MESSAGES":["*"],
                    "common.utility.locale.zh_CN.LC_MESSAGES":["*"],

                    "face_recognize_demo":["*"],
                    "face_recognize_demo.resource":["*"],
                    "face_recognize_demo.resource.photo_bg_res":["*"],
                    "face_recognize_demo.resource.qss":["*"],
                    "face_recognize_demo.configure_string":["*"],
                    "face_recognize_demo.language.local.en.LC_MESSAGES":["*"],
                    "face_recognize_demo.language.local.zh_CN.LC_MESSAGES":["*"],
                    "facemask_demo":["*"],
                    "facemask_demo.view":["*"],
                    "facemask_demo.view.resource":["*"],
                    "facemask_demo.view.resource.images":["*"],
                    "facemask_demo.config":["*"],
                    "facemask_demo.config.locale":["*"],
                    "facemask_demo.config.locale.en_US":["*"],
                    "facemask_demo.config.locale.en_US.LC_MESSAGES":["*"],
                    "facemask_demo.config.locale.zh_CN":["*"],
                    "facemask_demo.config.locale.zh_CN.LC_MESSAGES":["*"],
                    "object_detection_demo":["*"],
                    "object_detection_demo.config":["*"],
                    "object_detection_demo.config.locale":["*"],
                    "object_detection_demo.config.locale.en":["*"],
                    "object_detection_demo.config.locale.en.LC_MESSAGES":["*"],
                    "object_detection_demo.config.locale.zh_CN":["*"],
                    "object_detection_demo.config.locale.zh_CN.LC_MESSAGES":["*"],
                    "object_detection_demo.resource":["*"],
                    "object_detection_demo.resource.goods":["*"],
                    "object_detection_demo.resource.images":["*"],
                    "object_detection_demo.resource.qss":["*"],

                    "style_transfer_demo":["*"],
                    "style_transfer_demo.config":["*"],
                    "style_transfer_demo.config.locale":["*"],
                    "style_transfer_demo.config.locale.en":["*"],
                    "style_transfer_demo.config.locale.en.LC_MESSAGES":["*"],
                    "style_transfer_demo.config.locale.zh_CN":["*"],
                    "style_transfer_demo.config.locale.zh_CN.LC_MESSAGES":["*"],
                    "style_transfer_demo.resource":["*"],
                    "style_transfer_demo.resource.images":["*"],
                    "style_transfer_demo.resource.images.sample":["*"],
                    "style_transfer_demo.resource.images.style":["*"],
                    "style_transfer_demo.resource.qss":["*"],

                    "smart_photo_studio_demo":["*"],
                    "smart_photo_studio_demo.view":["*"],
                    "smart_photo_studio_demo.view.resource":["*"],
                    "smart_photo_studio_demo.view.resource.images":["*"],
                    "smart_photo_studio_demo.presenter":["*"],
                    "smart_photo_studio_demo.config.locale.en.LC_MESSAGES":["*"],
                    "smart_photo_studio_demo.config.locale.zh_CN.LC_MESSAGES":["*"],

                    "photo_to_cartoon_demo":["*"],
                    "photo_to_cartoon_demo.resources":["*"],
                    "photo_to_cartoon_demo.language.local.en.LC_MESSAGES":["*"],
                    "photo_to_cartoon_demo.language.local.zh_CN.LC_MESSAGES":["*"],

                    "yanshee_pose_imitate_demo":["*"],
                    "yanshee_pose_imitate_demo.resource":["*"],
                    "yanshee_pose_imitate_demo.resource.images":["*"],
                    "yanshee_pose_imitate_demo.resource.qss":["*"]
    },
    include_package_data = True,
    platforms = "any",
    install_requires = [
    ]
)
