# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Base(object):
    def setupUi(self, Base):
        Base.setObjectName("Base")
        Base.resize(961, 582)
        Base.setAutoFillBackground(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Base)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame = QtWidgets.QFrame(Base)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.card_icon = QtWidgets.QLabel(self.horizontalFrame)
        self.card_icon.setObjectName("card_icon")
        self.verticalLayout_5.addWidget(self.card_icon, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.top_layout = QtWidgets.QVBoxLayout()
        self.top_layout.setContentsMargins(0, -1, -1, -1)
        self.top_layout.setObjectName("top_layout")
        self.title = QtWidgets.QLabel(self.horizontalFrame)
        self.title.setObjectName("title")
        self.top_layout.addWidget(self.title)
        self.sub_title = QtWidgets.QLabel(self.horizontalFrame)
        self.sub_title.setObjectName("sub_title")
        self.top_layout.addWidget(self.sub_title)
        self.verticalLayout_7.addLayout(self.top_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main = QtWidgets.QFrame(self.horizontalFrame)
        self.main.setMinimumSize(QtCore.QSize(730, 0))
        self.main.setMaximumSize(QtCore.QSize(730, 16777215))
        self.main.setObjectName("main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_4.setContentsMargins(0, 0, 50, 20)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.camera = QtWidgets.QLabel(self.main)
        self.camera.setMinimumSize(QtCore.QSize(0, 0))
        self.camera.setMaximumSize(QtCore.QSize(640, 480))
        self.camera.setStyleSheet("")
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.verticalLayout_4.addWidget(self.camera)
        self.describe = QtWidgets.QLabel(self.main)
        self.describe.setObjectName("describe")
        self.verticalLayout_4.addWidget(self.describe)
        self.selected_list = QtWidgets.QListWidget(self.main)
        self.selected_list.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.selected_list.setObjectName("selected_list")
        self.verticalLayout_4.addWidget(self.selected_list, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.main)
        self.line = QtWidgets.QFrame(self.horizontalFrame)
        self.line.setMinimumSize(QtCore.QSize(1, 480))
        self.line.setMaximumSize(QtCore.QSize(1, 506))
        self.line.setStyleSheet("background-color: #4C788493;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QWidget(self.horizontalFrame)
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(50, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.threshold_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_label.sizePolicy().hasHeightForWidth())
        self.threshold_label.setSizePolicy(sizePolicy)
        self.threshold_label.setScaledContents(True)
        self.threshold_label.setObjectName("threshold_label")
        self.verticalLayout_3.addWidget(self.threshold_label, 0, QtCore.Qt.AlignVCenter)
        self.threshold = QtWidgets.QFrame(self.frame)
        self.threshold.setMinimumSize(QtCore.QSize(0, 50))
        self.threshold.setMaximumSize(QtCore.QSize(16777215, 150))
        self.threshold.setStyleSheet("")
        self.threshold.setObjectName("threshold")
        self.operate = QtWidgets.QVBoxLayout(self.threshold)
        self.operate.setContentsMargins(0, 0, 0, 0)
        self.operate.setSpacing(0)
        self.operate.setObjectName("operate")
        self.verticalLayout_3.addWidget(self.threshold)
        self.select_goods_label = QtWidgets.QLabel(self.frame)
        self.select_goods_label.setScaledContents(False)
        self.select_goods_label.setObjectName("select_goods_label")
        self.verticalLayout_3.addWidget(self.select_goods_label)
        self.select_goods_list = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_goods_list.sizePolicy().hasHeightForWidth())
        self.select_goods_list.setSizePolicy(sizePolicy)
        self.select_goods_list.setMinimumSize(QtCore.QSize(0, 0))
        self.select_goods_list.setMaximumSize(QtCore.QSize(800, 16777215))
        self.select_goods_list.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.select_goods_list.setObjectName("select_goods_list")
        self.verticalLayout_3.addWidget(self.select_goods_list)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout.addWidget(self.horizontalFrame)

        self.retranslateUi(Base)
        QtCore.QMetaObject.connectSlotsByName(Base)

    def retranslateUi(self, Base):
        _translate = QtCore.QCoreApplication.translate
        Base.setWindowTitle(_translate("Base", "Base"))
        self.card_icon.setText(_translate("Base", "card_icon"))
        self.title.setText(_translate("Base", "TextLabel"))
        self.sub_title.setText(_translate("Base", "TextLabel"))
        self.describe.setText(_translate("Base", "描述"))
        self.threshold_label.setText(_translate("Base", "置信度设置"))
        self.select_goods_label.setText(_translate("Base", "选择盘点物品"))

