# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yanshee.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Base(object):
    def setupUi(self, Base):
        Base.setObjectName("Base")
        Base.resize(1920, 1080)
        Base.setAutoFillBackground(True)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Base)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.root = QtWidgets.QFrame(Base)
        self.root.setLineWidth(0)
        self.root.setObjectName("root")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.root)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left = QtWidgets.QWidget(self.root)
        self.left.setMinimumSize(QtCore.QSize(150, 0))
        self.left.setMaximumSize(QtCore.QSize(150, 16777215))
        self.left.setObjectName("left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.card_icon = QtWidgets.QLabel(self.left)
        self.card_icon.setObjectName("card_icon")
        self.verticalLayout_3.addWidget(self.card_icon, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.left, 0, QtCore.Qt.AlignLeft)
        self.main = QtWidgets.QFrame(self.root)
        self.main.setMinimumSize(QtCore.QSize(0, 0))
        self.main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main.setObjectName("main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_4.setContentsMargins(0, 80, 0, 100)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top = QtWidgets.QWidget(self.main)
        self.top.setMaximumSize(QtCore.QSize(16777215, 200))
        self.top.setObjectName("top")
        self.top2 = QtWidgets.QVBoxLayout(self.top)
        self.top2.setContentsMargins(0, 0, 0, 0)
        self.top2.setSpacing(0)
        self.top2.setObjectName("top2")
        self.top_title = QtWidgets.QLabel(self.top)
        self.top_title.setStyleSheet("")
        self.top_title.setObjectName("top_title")
        self.top2.addWidget(self.top_title, 0, QtCore.Qt.AlignBottom)
        self.sub_title = QtWidgets.QLabel(self.top)
        self.sub_title.setStyleSheet("")
        self.sub_title.setObjectName("sub_title")
        self.top2.addWidget(self.sub_title, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.top2.addItem(spacerItem)
        self.top2.setStretch(0, 1)
        self.verticalLayout_4.addWidget(self.top)
        self.operate = QtWidgets.QWidget(self.main)
        self.operate.setMinimumSize(QtCore.QSize(1440, 0))
        self.operate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.operate.setObjectName("operate")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.operate)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.device = QtWidgets.QFrame(self.operate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device.sizePolicy().hasHeightForWidth())
        self.device.setSizePolicy(sizePolicy)
        self.device.setMinimumSize(QtCore.QSize(0, 0))
        self.device.setObjectName("device")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.device)
        self.verticalLayout_2.setContentsMargins(-1, 9, 9, 0)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dev_tit = QtWidgets.QLabel(self.device)
        self.dev_tit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dev_tit.sizePolicy().hasHeightForWidth())
        self.dev_tit.setSizePolicy(sizePolicy)
        self.dev_tit.setMinimumSize(QtCore.QSize(0, 34))
        self.dev_tit.setText("")
        self.dev_tit.setObjectName("dev_tit")
        self.verticalLayout_2.addWidget(self.dev_tit)
        self.dev_guide = QtWidgets.QFrame(self.device)
        self.dev_guide.setMinimumSize(QtCore.QSize(680, 510))
        self.dev_guide.setStyleSheet("")
        self.dev_guide.setObjectName("dev_guide")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dev_guide)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2.addWidget(self.dev_guide)
        self.dev_list = QtWidgets.QListWidget(self.device)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dev_list.sizePolicy().hasHeightForWidth())
        self.dev_list.setSizePolicy(sizePolicy)
        self.dev_list.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.dev_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dev_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dev_list.setAutoScroll(False)
        self.dev_list.setObjectName("dev_list")
        self.verticalLayout_2.addWidget(self.dev_list)
        self.horizontalLayout_2.addWidget(self.device)
        self.line = QtWidgets.QFrame(self.operate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 540))
        self.line.setMaximumSize(QtCore.QSize(1, 540))
        self.line.setStyleSheet("background-color: #4C788493;\n"
"margin-top:60px;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line, 0, QtCore.Qt.AlignTop)
        self.motion = QtWidgets.QFrame(self.operate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motion.sizePolicy().hasHeightForWidth())
        self.motion.setSizePolicy(sizePolicy)
        self.motion.setMinimumSize(QtCore.QSize(0, 0))
        self.motion.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.motion.setObjectName("motion")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.motion)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 0)
        self.verticalLayout_5.setSpacing(16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mot_tit = QtWidgets.QLabel(self.motion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mot_tit.sizePolicy().hasHeightForWidth())
        self.mot_tit.setSizePolicy(sizePolicy)
        self.mot_tit.setMinimumSize(QtCore.QSize(450, 34))
        self.mot_tit.setText("")
        self.mot_tit.setObjectName("mot_tit")
        self.verticalLayout_5.addWidget(self.mot_tit, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.motion_stack = QtWidgets.QStackedWidget(self.motion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motion_stack.sizePolicy().hasHeightForWidth())
        self.motion_stack.setSizePolicy(sizePolicy)
        self.motion_stack.setMinimumSize(QtCore.QSize(640, 480))
        self.motion_stack.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.motion_stack.setLineWidth(0)
        self.motion_stack.setObjectName("motion_stack")
        self.page_def = QtWidgets.QWidget()
        self.page_def.setMinimumSize(QtCore.QSize(640, 0))
        self.page_def.setObjectName("page_def")
        self.mot_perform = QtWidgets.QFrame(self.page_def)
        self.mot_perform.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.mot_perform.setObjectName("mot_perform")
        self.mot_default = QtWidgets.QFrame(self.mot_perform)
        self.mot_default.setGeometry(QtCore.QRect(129, 80, 401, 312))
        self.mot_default.setMinimumSize(QtCore.QSize(0, 312))
        self.mot_default.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.mot_default.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mot_default.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mot_default.setObjectName("mot_default")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mot_default)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_9.setSpacing(12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mot_icon = QtWidgets.QLabel(self.mot_default)
        self.mot_icon.setMinimumSize(QtCore.QSize(180, 280))
        self.mot_icon.setText("")
        self.mot_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.mot_icon.setObjectName("mot_icon")
        self.verticalLayout_9.addWidget(self.mot_icon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mot_txt = QtWidgets.QLabel(self.mot_default)
        self.mot_txt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mot_txt.sizePolicy().hasHeightForWidth())
        self.mot_txt.setSizePolicy(sizePolicy)
        self.mot_txt.setMinimumSize(QtCore.QSize(0, 0))
        self.mot_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.mot_txt.setObjectName("mot_txt")
        self.verticalLayout_9.addWidget(self.mot_txt, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.setStretch(0, 1)
        self.mot_oper = QtWidgets.QFrame(self.mot_perform)
        self.mot_oper.setGeometry(QtCore.QRect(374, 410, 251, 55))
        self.mot_oper.setMinimumSize(QtCore.QSize(0, 0))
        self.mot_oper.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.mot_oper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mot_oper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mot_oper.setObjectName("mot_oper")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mot_oper)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.mot_load = QtWidgets.QFrame(self.mot_perform)
        self.mot_load.setGeometry(QtCore.QRect(100, 145, 440, 190))
        self.mot_load.setStyleSheet("background-color:#CC000000;\n"
"border-radius: 8px;")
        self.mot_load.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mot_load.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mot_load.setObjectName("mot_load")
        self.load_icon = QtWidgets.QLabel(self.mot_load)
        self.load_icon.setGeometry(QtCore.QRect(199, 45, 44, 44))
        self.load_icon.setStyleSheet("background-color:#00000000;")
        self.load_icon.setObjectName("load_icon")
        self.load_txt = QtWidgets.QLabel(self.mot_load)
        self.load_txt.setGeometry(QtCore.QRect(131, 110, 197, 32))
        self.load_txt.setStyleSheet("background-color:#00000000;\n"
"font-size: 24px;\n"
"color:#FFFFFF;")
        self.load_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.load_txt.setObjectName("load_txt")
        self.motion_stack.addWidget(self.page_def)
        self.page_camera = QtWidgets.QWidget()
        self.page_camera.setMinimumSize(QtCore.QSize(640, 0))
        self.page_camera.setObjectName("page_camera")
        self.camera = QtWidgets.QLabel(self.page_camera)
        self.camera.setGeometry(QtCore.QRect(-1, -1, 640, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera.sizePolicy().hasHeightForWidth())
        self.camera.setSizePolicy(sizePolicy)
        self.camera.setMinimumSize(QtCore.QSize(640, 480))
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.mot_reset = QtWidgets.QFrame(self.page_camera)
        self.mot_reset.setGeometry(QtCore.QRect(374, 410, 251, 55))
        self.mot_reset.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.mot_reset.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mot_reset.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mot_reset.setObjectName("mot_reset")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mot_reset)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mot_count = QtWidgets.QLabel(self.page_camera)
        self.mot_count.setGeometry(QtCore.QRect(296, 169, 48, 58))
        self.mot_count.setText("")
        self.mot_count.setScaledContents(False)
        self.mot_count.setAlignment(QtCore.Qt.AlignCenter)
        self.mot_count.setObjectName("mot_count")
        self.mot_initial = QtWidgets.QFrame(self.page_camera)
        self.mot_initial.setGeometry(QtCore.QRect(80, 177, 440, 190))
        self.mot_initial.setStyleSheet("background-color:#CC000000;\n"
"border-radius: 8px;")
        self.mot_initial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mot_initial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mot_initial.setObjectName("mot_initial")
        self.ini_icon = QtWidgets.QLabel(self.mot_initial)
        self.ini_icon.setGeometry(QtCore.QRect(199, 38, 44, 44))
        self.ini_icon.setStyleSheet("background-color:#00000000;")
        self.ini_icon.setObjectName("ini_icon")
        self.ini_result = QtWidgets.QLabel(self.mot_initial)
        self.ini_result.setGeometry(QtCore.QRect(78, 91, 281, 32))
        self.ini_result.setStyleSheet("background-color:#00000000;\n"
"font-size: 24px;\n"
"color:#FFFFFF;")
        self.ini_result.setAlignment(QtCore.Qt.AlignCenter)
        self.ini_result.setObjectName("ini_result")
        self.ini_tip = QtWidgets.QLabel(self.mot_initial)
        self.ini_tip.setGeometry(QtCore.QRect(13, 132, 411, 44))
        self.ini_tip.setStyleSheet("background-color:#00000000;\n"
"font-size: 18px;\n"
"color:#99FFFFFF;")
        self.ini_tip.setAlignment(QtCore.Qt.AlignCenter)
        self.ini_tip.setObjectName("ini_tip")
        self.mot_robot = QtWidgets.QLabel(self.page_camera)
        self.mot_robot.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.mot_robot.setText("")
        self.mot_robot.setScaledContents(False)
        self.mot_robot.setAlignment(QtCore.Qt.AlignCenter)
        self.mot_robot.setObjectName("mot_robot")
        self.mot_title = QtWidgets.QLabel(self.page_camera)
        self.mot_title.setGeometry(QtCore.QRect(120, 20, 381, 48))
        self.mot_title.setStyleSheet("font-size: 16px;\n"
"color: #FFFFFF;")
        self.mot_title.setText("")
        self.mot_title.setScaledContents(False)
        self.mot_title.setAlignment(QtCore.Qt.AlignCenter)
        self.mot_title.setObjectName("mot_title")
        self.mot_tit_icon = QtWidgets.QLabel(self.page_camera)
        self.mot_tit_icon.setGeometry(QtCore.QRect(200, 30, 28, 28))
        self.mot_tit_icon.setStyleSheet("")
        self.mot_tit_icon.setText("")
        self.mot_tit_icon.setScaledContents(False)
        self.mot_tit_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.mot_tit_icon.setObjectName("mot_tit_icon")
        self.camera.raise_()
        self.mot_count.raise_()
        self.mot_title.raise_()
        self.mot_tit_icon.raise_()
        self.mot_robot.raise_()
        self.mot_reset.raise_()
        self.mot_initial.raise_()
        self.motion_stack.addWidget(self.page_camera)
        self.verticalLayout_5.addWidget(self.motion_stack, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.motion, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout_4.addWidget(self.operate, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.main, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_3.addWidget(self.root)

        self.retranslateUi(Base)
        self.motion_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Base)

    def retranslateUi(self, Base):
        _translate = QtCore.QCoreApplication.translate
        Base.setWindowTitle(_translate("Base", "Base"))
        self.card_icon.setText(_translate("Base", "TextLabel"))
        self.top_title.setText(_translate("Base", "主标题"))
        self.sub_title.setText(_translate("Base", "副标题"))
        self.mot_txt.setText(_translate("Base", "TextLabel"))
        self.load_icon.setText(_translate("Base", "TextLabel"))
        self.load_txt.setText(_translate("Base", "TextLabel"))
        self.ini_icon.setText(_translate("Base", "TextLabel"))
        self.ini_result.setText(_translate("Base", "TextLabel"))
        self.ini_tip.setText(_translate("Base", "TextLabel"))

